version: "3.7"
services:

  http:
    container_name: tfc_http
    image: nginx
    networks:
      - tfc_default
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf/dev/nginx.dev.conf:/etc/nginx/conf.d/default.conf

  app:
    container_name: tfc_app
    build:
      context: docker/app
      dockerfile: Dockerfile
    networks:
      - tfc_default
    depends_on:
      - db
    volumes:
      - .:/var/www
      - ./docker/app/conf/php.ini:/usr/local/etc/php/php.ini
      - ./docker/app/conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

  db:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    container_name: tfc_db
    environment:
      POSTGRES_DB: tfc
      POSTGRES_PASSWORD: passwd
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    networks:
      - tfc_default
    volumes:
      - db_data:/var/lib/postgresql/data:rw

networks:
  tfc_default:

volumes:
  db_data:
